version: '3.9'
services:

  nginx:
    build: ./nginx
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:12.0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    depends_on:
      - db
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn server.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media

volumes:
  media_volume:
  static_volume:
  postgres_data:
